version: '2'
services:
 postgres1:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=camunda-test
     - POSTGRES_USER=camunda-test
     - POSTGRES_PASSWORD=camunda-test
     - MAX_CONNECTIONS=300
